/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContattiRouteImport } from './routes/contatti'
import { Route as LavoraConNoiRouteImport } from './routes/lavora-con-noi'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as RecensioniRouteImport } from './routes/recensioni'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContattiRoute = ContattiRouteImport.update({
  id: '/contatti',
  path: '/contatti',
  getParentRoute: () => rootRouteImport,
} as any)
const LavoraConNoiRoute = LavoraConNoiRouteImport.update({
  id: '/lavora-con-noi',
  path: '/lavora-con-noi',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const RecensioniRoute = RecensioniRouteImport.update({
  id: '/recensioni',
  path: '/recensioni',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contatti': typeof ContattiRoute
  '/lavora-con-noi': typeof LavoraConNoiRoute
  '/menu': typeof MenuRoute
  '/recensioni': typeof RecensioniRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contatti': typeof ContattiRoute
  '/lavora-con-noi': typeof LavoraConNoiRoute
  '/menu': typeof MenuRoute
  '/recensioni': typeof RecensioniRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contatti': typeof ContattiRoute
  '/lavora-con-noi': typeof LavoraConNoiRoute
  '/menu': typeof MenuRoute
  '/recensioni': typeof RecensioniRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contatti' | '/lavora-con-noi' | '/menu' | '/recensioni'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contatti' | '/lavora-con-noi' | '/menu' | '/recensioni'
  id:
    '__root__' | '/' | '/contatti' | '/lavora-con-noi' | '/menu' | '/recensioni'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContattiRoute: typeof ContattiRoute
  LavoraConNoiRoute: typeof LavoraConNoiRoute
  MenuRoute: typeof MenuRoute
  RecensioniRoute: typeof RecensioniRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatti': {
      id: '/contatti'
      path: '/contatti'
      fullPath: '/contatti'
      preLoaderRoute: typeof ContattiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lavora-con-noi': {
      id: '/lavora-con-noi'
      path: '/lavora-con-noi'
      fullPath: '/lavora-con-noi'
      preLoaderRoute: typeof LavoraConNoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recensioni': {
      id: '/recensioni'
      path: '/recensioni'
      fullPath: '/recensioni'
      preLoaderRoute: typeof RecensioniRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContattiRoute: ContattiRoute,
  LavoraConNoiRoute: LavoraConNoiRoute,
  MenuRoute: MenuRoute,
  RecensioniRoute: RecensioniRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
